apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-2
  description: "test-2"
  annotations:
    github.com/project-slug: group:default/admins/undefined
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: test2
    backstage.io/kubernetes-cluster: minikube
    backstage.io/kubernetes-namespace: default
    argocd/app-name: test-2
    app.kubernetes.io/name: nginx
  links:
    - url: https://example.cm
      title: test-2-link-1
      icon: web
      type: App frontend
  tags:
    - web
    - html
    - frontend
spec:
  type: service
  lifecycle: integration
  owner: "group:default/admins"
  system: "system:default/basicweb"
  description: Project based on local template of Basic web frontend (HW) service
  host: github.com
  consumesApis:
    - NaN
