apiVersion: v1
kind: Service
metadata:
  name: test-2-service
  labels:
    backstage.io/kubernetes-id: test2
spec:
  selector:
    app: test-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32223
  type: NodePort