apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-2-deployment
  labels:
    backstage.io/kubernetes-id: test2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-2
  template:
    metadata:
      labels:
        app: test-2
        backstage.io/kubernetes-id: test2
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-assets-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web-assets-volume